import React,{useState}from"react";
import{createRoot}from"react-dom/client";
import{Activity,Users,Building2,Eye,MapPinned,ArrowUpRight,Menu,Info,ShieldCheck,Database,ArrowRight}from"lucide-react";
import{BarChart,Bar,XAxis,YAxis,CartesianGrid,Tooltip,ResponsiveContainer}from"recharts";
import"./styles.css";

const R={residents:239,enterprises:155,tourists:"≈320",livelihood:"≈49%",development:"63.8%",water:"43.7%",piped:"7.26 h/day",shortage:"42.6%",impact:"43.1%",or:"6.73",accom:"65.5%",retail:"22.7%",experience:"3.78/5",cleanliness:"3.46/5",rho:"0.485"};
const NAV=[["overview","Overview",Activity],["residents","Residents",Users],["enterprises","Enterprises",Building2],["visitors","Visitors",Eye],["spatial","Spatial evidence",MapPinned],["framework","Monitoring framework",ArrowUpRight]];

function Metric({label,value,sub}){return <div className="metric"><small>{label}</small><strong>{value}</strong>{sub&&<span>{sub}</span>}</div>}
function Card({title,eyebrow,children}){return <section className="card">{eyebrow&&<small className="ey">{eyebrow}</small>}<h3>{title}</h3>{children}</section>}
function Header({eyebrow,title,text}){return <header className="header"><small>{eyebrow}</small><h1>{title}</h1><p>{text}</p></header>}
function Caveat({children}){return <div className="caveat"><Info size={14}/><span>{children}</span></div>}
function Bars({data}){return <ResponsiveContainer width="100%" height={225}><BarChart data={data} margin={{top:8,right:10,left:-22,bottom:8}}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="name" tick={{fontSize:10}}/><YAxis domain={[0,100]} tick={{fontSize:9}} tickFormatter={v=>`${v}%`}/><Tooltip formatter={v=>`${v}%`}/><Bar dataKey="value" fill="#315f52" radius={[5,5,0,0]}/></BarChart></ResponsiveContainer>}
function Finding({title,children}){return <div className="finding"><b>{title}</b><span>{children}</span></div>}

function Overview(){return <>
<div className="hero"><div><small>FIELD-BASED BASELINE · 22 JUNE–2 JULY 2026</small><h1>Does tourism pressure affect everyone equally?</h1><p>This study does not treat “tourism pressure” as a single measured variable. It examines economic dependence, resource exposure, operational sensitivity and spatial exposure, and asks whether they identify the same actors as vulnerable.</p><button onClick={()=>window.dispatchEvent(new CustomEvent("go",{detail:"spatial"}))}>See the spatial test <ArrowRight size={13}/></button></div><div className="heroStats"><div><b>OR 6.73</b><span>reported water shortage and operational disruption</span></div><div><b>p = .174</b><span>lake-proximity test</span></div></div></div>
<div className="metrics"><Metric label="Residents" value={R.residents} sub="available observations"/><Metric label="Enterprises" value={R.enterprises} sub="after record removal"/><Metric label="Tourists" value={R.tourists} sub="approximate survey count"/><Metric label="Tourism primary livelihood" value={R.livelihood} sub="resident sample"/></div>
<div className="grid two"><Card eyebrow="What the data show" title="Four findings"><Finding title="Economic embeddedness">Tourism is economically important and positively valued by surveyed residents.</Finding><Finding title="Household resource conditions">Tourism dependence does not identify households reporting greater water stress.</Finding><Finding title="Enterprise sensitivity">Direct peak-season water shortage is strongly associated with operational disruption.</Finding><Finding title="Spatial exposure">Lake distance does not significantly distinguish impacted enterprises.</Finding></Card>
<Card eyebrow="Interpretation" title="Pressure is multidimensional"><div className="dims">{[["Economic dependence","importance of tourism to livelihoods"],["Resource exposure","encountering a water constraint"],["Operational sensitivity","degree of disruption when constraints occur"],["Spatial exposure","whether location is a useful proxy"]].map(x=><div key={x[0]}><b>{x[0]}</b><span>{x[1]}</span></div>)}</div><Caveat>These dimensions are analysed separately. The dashboard does not create a composite “tourism pressure” score.</Caveat></Card></div>
<Card title="What this dashboard is — and is not"><div className="not"><div><ShieldCheck size={17}/><p><b>It is:</b> a visual baseline of the empirical findings and a structure for repeated destination monitoring.</p></div><div><Database size={17}/><p><b>It is not:</b> a real-time system, causal model, predictive model, or validated intervention-priority index.</p></div></div></Card>
</>}

function Residents(){return <><Header eyebrow="01 · RESIDENTS" title="Tourism is economically embedded, but dependence does not identify household water stress." text="Resident responses separate tourism’s economic importance from household resource conditions."/>
<div className="metrics"><Metric label="Primary livelihood" value={R.livelihood}/><Metric label="Tourism contributes to development" value={R.development} sub="143/224 valid"/><Metric label="Worsening water availability" value={R.water}/><Metric label="Mean piped-water availability" value={R.piped}/></div>
<div className="grid two"><Card title="Tourism and perceived development"><Bars data={[{name:"Dependent",value:69.4},{name:"Non-dependent",value:58}]}/><p className="note">Adjusted OR = 2.10 · 95% CI 1.12–3.95 · p=.021.</p></Card>
<Card title="Water-related findings"><div className="rows"><div><span>Tourism dependence → worsening availability</span><b>OR .935 · p=.811</b></div><div><span>Tourism dependence → private-water procurement</span><b>OR 1.20 · p=.596</b></div><div><span>Infrastructure inadequacy → worsening availability</span><b>exploratory association</b></div><div><span>Seasonal sewage overflow → worsening availability</span><b>exploratory association</b></div></div><Caveat>Tourism dependence is an economic-position variable, not a reliable stand-alone proxy for household water vulnerability in this sample.</Caveat></Card></div>
<Card title="Resident interpretation"><p className="large">Households can be economically dependent on tourism without being more likely to report worsening water conditions. The economic and resource dimensions therefore need to be monitored separately.</p></Card></>}

function Enterprises(){return <><Header eyebrow="02 · ENTERPRISES" title="Direct water exposure is more closely tied to disruption than location." text="Enterprise data provide the strongest inferential relationship in the study."/>
<div className="metrics"><Metric label="Peak-season shortage" value={R.shortage} sub="23/54 valid"/><Metric label="Operational impact ≤2 km" value={R.impact} sub="22/51 valid"/><Metric label="Shortage → disruption" value={`OR ${R.or}`} sub="95% CI 1.72–26.24 · p=.006"/><Metric label="Accommodation/Food impact" value={R.accom} sub={`Retail/Other ${R.retail}`}/></div>
<div className="grid two"><Card title="Operational impact by reported shortage"><Bars data={[{name:"Shortage",value:76.2},{name:"No shortage",value:26.7}]}/><p className="note">Adjusted logistic regression: OR=6.73 · p=.006. This is an association, not a causal estimate.</p></Card>
<Card title="Sensitivity differs by enterprise type"><Bars data={[{name:"Accommodation/Food",value:65.5},{name:"Retail/Other",value:22.7}]}/><p className="note">Retail/Other relative to Accommodation/Food: adjusted OR=.21 · 95% CI .05–.85 · p=.028.</p></Card></div>
<Card title="Observed adaptation"><div className="tags">{["Water storage","Alternative supply","Consumption reduction","Operating changes","Service / booking restrictions","Rainwater harvesting"].map(x=><span key={x}>{x}</span>)}</div><p className="note">Qualitative typology from substantive responses; not a prevalence estimate.</p></Card></>}

function Visitors(){return <><Header eyebrow="03 · VISITORS" title="Destination conditions are reflected in visitor experience." text="Visitor responses provide a separate demand-side perspective."/><div className="metrics"><Metric label="Overall experience" value={R.experience}/><Metric label="Perceived cleanliness" value={R.cleanliness}/><Metric label="Cleanliness ↔ experience" value={`ρ=${R.rho}`} sub="p<.001"/><Metric label="Analytical role" value="Demand-side"/></div>
<Card title="What this result means"><div className="visitor"><strong>ρ = .485</strong><div><h3>Cleanliness is positively associated with overall experience.</h3><p>This is a downstream destination-quality indicator. It does not establish causality or connect visitor experience directly to household or enterprise water stress.</p></div></div></Card>
<Card title="Why visitors remain separate"><p className="large">Residents, enterprises and visitors occupy different positions within the destination system. Combining their responses into a single score would obscure the differences the study is designed to examine.</p></Card></>}

function Spatial(){const cells=[["Cell 1",0,7],["Cell 2",14.3,7],["Cell 3",50,4],["Cell 4",50,6],["Cell 5",53.8,13],["Cell 6",80,5],["Cell 7",100,3]];return <><Header eyebrow="04 · SPATIAL EVIDENCE" title="Location alone does not identify which enterprises are affected." text="The spatial analysis tests whether proximity to Nainital Lake can act as a stand-alone proxy for reported enterprise operational impact."/>
<div className="metrics"><Metric label="Primary spatial sample" value="51" sub="valid impact responses within 2 km"/><Metric label="Impacted" value="22 · 43.1%" sub="primary spatial sample"/><Metric label="Impacted median distance" value="187.98 m"/><Metric label="Proximity test" value="U=391" sub="p=.174"/></div>
<div className="grid two"><Card title="What is actually being tested"><div className="spatialLogic"><div><small>Exposure proxy</small><b>Distance to lake boundary</b></div><ArrowRight size={15}/><div><small>Outcome</small><b>Reported operational impact</b></div><ArrowRight size={15}/><div><small>Test</small><b>Mann–Whitney U</b></div></div><Caveat>A non-significant proximity test means lake distance alone was insufficient to distinguish impacted from non-impacted enterprises in this sample. It does not mean geography is irrelevant.</Caveat></Card>
<Card title="Primary vs robustness estimate"><div className="compare"><div><small>≤2 km</small><b>22 / 51</b><strong>43.1%</strong></div><div><small>All valid geolocated</small><b>25 / 57</b><strong>43.9%</strong></div></div><p className="note">Unrestricted proximity test: U=480 · p=.201.</p></Card></div>
<Card title="Cell-level evidence — reported rates only"><p className="note">Seven cells meet the minimum reporting threshold of n≥3. These are analytical results, not geographic “hotspots.” The 100% cell has n=3 and is flagged accordingly.</p><div className="cells">{cells.map(x=><div className="cell" key={x[0]}><span><b>{x[0]}</b> <small>n={x[2]}</small></span><div><i style={{width:`${x[1]}%`}}/></div><strong>{x[1]}%</strong>{x[2]<5?<em>low n</em>:<em/>}</div>)}</div><Caveat>The dashboard intentionally does not display enterprise point coordinates until the geolocation QA/export is validated. This prevents uncertain coordinates from being presented as confirmed survey locations.</Caveat></Card>
<Card title="Spatial integrity"><div className="not"><div><ShieldCheck size={17}/><p><b>Reported:</b> the aggregate spatial results and statistical tests used in the paper.</p></div><div><MapPinned size={17}/><p><b>Withheld:</b> unvalidated point locations. A verified GeoJSON layer can be added later without changing the statistics.</p></div></div></Card></>}

function Framework(){const items=[["Economic position","Tourism dependence and perceived contribution to local development."],["Resource exposure","Household water conditions and enterprise peak-season shortage."],["Sensitivity","Operational disruption and differences by enterprise type."],["Adaptive capacity","Storage, alternative supply, consumption reduction and operating adjustments."],["Tourism outcomes","Resident perceptions and visitor experience."],["Spatial context","Lake proximity and cell-level distribution, interpreted cautiously."]];return <><Header eyebrow="05 · MONITORING FRAMEWORK" title="A baseline for repeated monitoring, not an intervention algorithm." text="The framework preserves the distinctions found in the empirical analysis and can be expanded as better spatial and longitudinal data become available."/><div className="grid two">{items.map((x,i)=><Card key={x[0]} eyebrow={`0${i+1}`} title={x[0]}><p className="large">{x[1]}</p></Card>)}</div><Card title="Proposed monitoring cycle"><div className="cycle">{["Collect stakeholder data","Check exposure","Identify sensitivity","Record adaptation","Compare rounds","Review interventions"].map((x,i)=><React.Fragment key={x}><span>{x}</span>{i<5&&<ArrowRight size={14}/>}</React.Fragment>)}</div></Card><Card title="What future rounds could add"><div className="future"><div><b>Repeated measurement</b><span>Track change across seasons.</span></div><div><b>Validated geospatial layer</b><span>Add QA-checked enterprise and amenity locations.</span></div><div><b>Longitudinal modelling</b><span>Test temporal relationships rather than relying on one cross-sectional round.</span></div><div><b>Decision support</b><span>Develop prioritisation rules only after repeated, validated data.</span></div></div></Card><Caveat>The present study does not claim to have built a predictive early-warning system or validated policy-priority index.</Caveat></>}

function App(){const[page,setPage]=useState("overview"),[open,setOpen]=useState(false);React.useEffect(()=>{const h=e=>setPage(e.detail);addEventListener("go",h);return()=>removeEventListener("go",h)},[]);const pages={overview:<Overview/>,residents:<Residents/>,enterprises:<Enterprises/>,visitors:<Visitors/>,spatial:<Spatial/>,framework:<Framework/>};return <div className="app"><aside className={open?"open":""}><div className="brand"><div className="logo">N</div><div><b>Nainital</b><small>Tourism & Resource Monitor</small></div></div><nav>{NAV.map(([id,label,Icon])=><button key={id} className={page===id?"active":""} onClick={()=>{setPage(id);setOpen(false)}}><Icon size={15}/>{label}</button>)}</nav><div className="side"><small>FIELD BASELINE</small><b>22 Jun — 2 Jul 2026</b><p>Resident · enterprise · visitor · spatial evidence</p></div></aside><button className="mobile" onClick={()=>setOpen(!open)}><Menu/></button><main className="main"><div className="topbar"><span>NAINITAL · SUSTAINABLE TOURISM FIELDWORK</span><span>BSASS · CROSS-SECTIONAL BASELINE</span></div><div className="content">{pages[page]}</div><footer><span>Primary data: 22 June–2 July 2026.</span><span>Baseline dashboard · not a predictive early-warning system.</span></footer></main></div>}
createRoot(document.getElementById("root")).render(<App/>);
